/* Curated real technology graph (source). Each entry: [id, English Wikipedia title, year, parentA, parentB, display name?]
 * Axioms (no parents) exist in 1900. Every later technology names its two key ingredients — a simplification:
 * real inventions draw on many things, but the model combines ideas in pairs.
 * tools/build-techgraph.js enriches this from Wikidata into data/techgraph.js.
 */
module.exports = [
  // ---- axioms: the world's toolkit in 1900 ----
  ['plough', 'Plough', -3000], ['glass', 'Glass', -2500], ['printing', 'Printing press', 1440],
  ['optics', 'Optics', 1600], ['microscope', 'Microscope', 1620], ['calculus', 'Calculus', 1670],
  ['calculator', 'Mechanical calculator', 1642], ['steam', 'Steam engine', 1712], ['statistics', 'Statistics', 1750],
  ['lithography', 'Lithography', 1796], ['battery', 'Electric battery', 1800], ['vaccine', 'Vaccine', 1796],
  ['railway', 'Rail transport', 1825], ['electromag', 'Electromagnetism', 1820], ['motor', 'Electric motor', 1834],
  ['photo', 'Photography', 1826], ['telegraph', 'Electrical telegraph', 1837], ['vulcan', 'Vulcanization', 1839],
  ['anaesthesia', 'General anaesthesia', 1846], ['thermo', 'Thermodynamics', 1850], ['gyro', 'Gyroscope', 1852],
  ['boolean', 'Boolean algebra', 1854], ['bessemer', 'Bessemer process', 1856], ['orgchem', 'Organic chemistry', 1828],
  ['oilwell', 'Oil well', 1859], ['refinery', 'Oil refinery', 1861], ['germ', 'Germ theory of disease', 1861],
  ['dynamite', 'Dynamite', 1867], ['generator', 'Electric generator', 1866], ['refrig', 'Refrigeration', 1876],
  ['telephone', 'Telephone', 1876], ['phonograph', 'Phonograph', 1877], ['bulb', 'Incandescent light bulb', 1879],
  ['piezo', 'Piezoelectricity', 1880], ['turbine', 'Steam turbine', 1884], ['car', 'Car', 1886],
  ['ac', 'Alternating current', 1886], ['glider', 'Glider (aircraft)', 1891], ['punchcard', 'Punched card', 1890],
  ['diesel', 'Diesel engine', 1893], ['icengine', 'Internal combustion engine', 1876], ['moviecam', 'Movie camera', 1888],
  ['xray', 'X-ray', 1895], ['radioact', 'Radioactivity', 1896], ['crt', 'Cathode-ray tube', 1897],
  ['vacpump', 'Vacuum pump', 1650],

  // ---- the 20th and 21st centuries ----
  ['radio', 'Radio', 1901, 'electromag', 'telegraph'],
  ['aircon', 'Air conditioning', 1902, 'refrig', 'motor'],
  ['vacuumclean', 'Vacuum cleaner', 1901, 'motor', 'vacpump'],
  ['airplane', 'Airplane', 1903, 'icengine', 'glider'],
  ['vactube', 'Vacuum tube', 1904, 'bulb', 'vacpump'],
  ['photoelec', 'Photoelectric effect', 1905, 'electromag', 'crt'],
  ['tractor', 'Tractor', 1901, 'icengine', 'plough'],
  ['cellculture', 'Cell culture', 1907, 'germ', 'microscope'],
  ['bakelite', 'Bakelite', 1907, 'orgchem', 'vulcan'],
  ['haber', 'Haber process', 1909, 'thermo', 'orgchem'],
  ['superconduct', 'Superconductivity', 1911, 'refrig', 'electromag'],
  ['assembly', 'Assembly line', 1913, 'car', 'railway'],
  ['grid', 'Electrical grid', 1910, 'ac', 'turbine'],
  ['sonar', 'Sonar', 1915, 'piezo', 'telephone'],
  ['rocket', 'Liquid-propellant rocket', 1926, 'refinery', 'gyro'],
  ['quantum', 'Quantum mechanics', 1925, 'radioact', 'calculus'],
  ['television', 'Television', 1927, 'crt', 'radio'],
  ['soundfilm', 'Sound film', 1927, 'phonograph', 'moviecam'],
  ['quartzclock', 'Quartz clock', 1927, 'piezo', 'vactube'],
  ['penicillin', 'Penicillin', 1928, 'germ', 'cellculture'],
  ['magtape', 'Magnetic tape', 1928, 'phonograph', 'electromag'],
  ['neutron', 'Neutron', 1932, 'radioact', 'xray'],
  ['polyethylene', 'Polyethylene', 1933, 'refinery', 'haber'],
  ['nylon', 'Nylon', 1935, 'bakelite', 'refinery'],
  ['radar', 'Radar', 1935, 'radio', 'vactube'],
  ['turingm', 'Turing machine', 1936, 'boolean', 'calculator'],
  ['helicopter', 'Helicopter', 1936, 'airplane', 'gyro'],
  ['jet', 'Jet engine', 1937, 'airplane', 'turbine'],
  ['synthrubber', 'Synthetic rubber', 1935, 'vulcan', 'polyethylene'],
  ['fission', 'Nuclear fission', 1938, 'neutron', 'quantum'],
  ['nmr', 'Nuclear magnetic resonance', 1938, 'quantum', 'radio'],
  ['xerography', 'Xerography', 1938, 'photo', 'photoelec'],
  ['reactor', 'Nuclear reactor', 1942, 'fission', 'turbine'],
  ['eniac', 'ENIAC', 1945, 'vactube', 'turingm'],
  ['microwave', 'Microwave oven', 1945, 'radar', 'motor'],
  ['transistor', 'Transistor', 1947, 'quantum', 'vactube'],
  ['infotheory', 'Information theory', 1948, 'telephone', 'boolean'],
  ['fracking', 'Hydraulic fracturing', 1947, 'oilwell', 'dynamite'],
  ['maser', 'Maser', 1953, 'quantum', 'radar'],
  ['dna', 'DNA', 1953, 'xray', 'orgchem'],
  ['nuclearpower', 'Nuclear power', 1954, 'reactor', 'generator'],
  ['solarcell', 'Solar cell', 1954, 'photoelec', 'transistor'],
  ['atomicclock', 'Atomic clock', 1955, 'quantum', 'maser'],
  ['polio', 'Polio vaccine', 1955, 'vaccine', 'cellculture'],
  ['container', 'Containerization', 1956, 'diesel', 'railway'],
  ['hdd', 'Hard disk drive', 1956, 'magtape', 'eniac'],
  ['vtr', 'Videotape', 1956, 'magtape', 'television'],
  ['ultrasound', 'Medical ultrasound', 1956, 'sonar', 'crt'],
  ['satellite', 'Satellite', 1957, 'rocket', 'radio'],
  ['ic', 'Integrated circuit', 1958, 'transistor', 'lithography'],
  ['ml', 'Machine learning', 1959, 'eniac', 'statistics'],
  ['laser', 'Laser', 1960, 'maser', 'optics'],
  ['led', 'Light-emitting diode', 1962, 'transistor', 'bulb'],
  ['greenrev', 'Green Revolution', 1960, 'haber', 'tractor'],
  ['compgraphics', 'Computer graphics', 1963, 'eniac', 'crt'],
  ['packet', 'Packet switching', 1965, 'infotheory', 'telephone'],
  ['hypertext', 'Hypertext', 1965, 'printing', 'eniac'],
  ['lcd', 'Liquid-crystal display', 1968, 'ic', 'orgchem'],
  ['ccd', 'Charge-coupled device', 1969, 'photoelec', 'ic'],
  ['arpanet', 'ARPANET', 1969, 'packet', 'ic'],
  ['restriction', 'Restriction enzyme', 1970, 'dna', 'germ'],
  ['fiber', 'Optical fiber', 1970, 'laser', 'glass'],
  ['microprocessor', 'Microprocessor', 1971, 'ic', 'eniac'],
  ['ctscan', 'CT scan', 1971, 'xray', 'ic'],
  ['mri', 'Magnetic resonance imaging', 1977, 'nmr', 'ic'],
  ['recombinant', 'Recombinant DNA', 1973, 'restriction', 'dna'],
  ['mobile', 'Mobile phone', 1973, 'radio', 'ic'],
  ['barcode', 'Barcode', 1974, 'laser', 'punchcard'],
  ['monoclonal', 'Monoclonal antibody', 1975, 'cellculture', 'dna'],
  ['digicam', 'Digital camera', 1975, 'ccd', 'photo'],
  ['publickey', 'Public-key cryptography', 1976, 'infotheory', 'turingm'],
  ['pc', 'Personal computer', 1977, 'microprocessor', 'television'],
  ['gps', 'Global Positioning System', 1978, 'satellite', 'atomicclock'],
  ['flash', 'Flash memory', 1980, 'ic', 'quantum'],
  ['cd', 'Compact disc', 1982, 'laser', 'phonograph'],
  ['internet', 'Internet', 1983, 'arpanet', 'pc'],
  ['pcr', 'Polymerase chain reaction', 1983, 'recombinant', 'thermo'],
  ['liion', 'Lithium-ion battery', 1991, 'battery', 'orgchem'],
  ['www', 'World Wide Web', 1991, 'internet', 'hypertext'],
  ['gmcrops', 'Genetically modified crops', 1994, 'recombinant', 'greenrev'],
  ['searchengine', 'Search engine', 1995, 'www', 'ml'],
  ['gpu', 'Graphics processing unit', 1999, 'microprocessor', 'compgraphics'],
  ['genome', 'Human Genome Project', 2003, 'pcr', 'pc'],
  ['socialmedia', 'Social media', 2004, 'www', 'digicam'],
  ['smartphone', 'Smartphone', 2007, 'mobile', 'www'],
  ['bitcoin', 'Bitcoin', 2008, 'publickey', 'internet'],
  ['ev', 'Electric vehicle', 2008, 'liion', 'car'],
  ['drone', 'Unmanned aerial vehicle', 2010, 'airplane', 'gps'],
  ['deeplearning', 'Deep learning', 2012, 'ml', 'gpu'],
  ['crispr', 'CRISPR gene editing', 2012, 'genome', 'recombinant'],
  ['llm', 'Large language model', 2018, 'deeplearning', 'www'],
  ['mrna', 'MRNA vaccine', 2020, 'recombinant', 'vaccine', 'mRNA vaccine']
];
